apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-cis
spec:
  template:
    spec:
      securityContext:
        hostPID: true
        hostNetwork: false
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: kube-bench-cis
        image: aquasec/kube-bench:latest
        args:
        - eks
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: lib-systemd
          mountPath: /lib/systemd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
      volumes:
      - name: var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: etc-systemd
        hostPath:
          path: /etc/systemd
      - name: lib-systemd
        hostPath:
          path: /lib/systemd
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
  restartPolicy: Never